
GET http://localhost:4000/products

# POST http://localhost:3000/category
# Content-Type: application/json

# {
#   "name": "New Category",
#   "description": "Category Description"
# }

# PATCH http://localhost:3000/category/68f78cc2b5ca57b4c9d9e6f7
# Content-Type: application/json

# {
#   "name": "Updated Category Name",
#   "description": "Updated Description"
# }

# DELETE http://localhost:3000/category/68f78c04204dde2839a07769


