
# GET http://localhost:4000/products

POST  http://localhost:4001/auth/signin
Content-Type: application/json
{
    "email": "tina@mail.com",
    "password": "tinatina"
}


### Inventory Endpoints

# @name getAllInventory
GET http://localhost:4000/inventory

### Get stock for a specific product
# @name getStock
GET http://localhost:4000/inventory/{{productId}}

### Update stock (Requires Auth)
# @name updateStock
POST http://localhost:4000/inventory/update
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productId": "{{productId}}",
    "quantity": 50
}

### Audit Trail Endpoints

# @name getAllMovements
GET http://localhost:4000/inventory/movements

### Get movements for a specific product
# @name getProductMovements
GET http://localhost:4000/inventory/{{productId}}/movements


