export enum StockMovementType {
  INCOMING = 'INCOMING',
  RESERVATION = 'RESERVATION',
  RELEASE = 'RELEASE',
  FINALIZATION = 'FINALIZATION',
  ADJUSTMENT = 'ADJUSTMENT',
  SCRAPPED = 'SCRAPPED',
  RETURN_CUSTOMER = 'RETURN_CUSTOMER',
  RETURN_SUPPLIER = 'RETURN_SUPPLIER',
}
